### ISSUE TITLE
Provide logo

### ISSUE THREAD

**Issue by danilobuerger** [coffeestats/coffeestats-ios#3]
@jandd is the coffeestats logo available as vector?

**Comment by jandd** [comment]
https://github.com/coffeestats/coffeestats-django/blob/master/coffeestats/static/images/coffeestats-logo.svg

**Comment by danilobuerger** [comment]
Fixed by https://github.com/coffeestats/coffeestats-ios/commit/c44274c074868140b46fca9bc0603ebfdf6dfca2
